image: docker:git
services:
  - docker:dind
stages:
  - test
  - build
  - development
  - deploy
test:
  stage: test
  script:
    - cd Excel-Events-Backend
    - docker build -t tests -f Tests.Dockerfile .
    - docker run tests
  tags:
    - docker
build:
  stage: build
  script:
    - docker login -u excelmec -p $DOCKER_HUB_PASSWORD
    - cd Excel-Events-Backend
    - docker build -t $DOCKER_IMAGE_NAME:staging -f Production.Dockerfile .
    - docker push $DOCKER_IMAGE_NAME:staging
  tags:
    - docker
  only:
    - master@excel-mec/excel-events/excel-events-service

deploy:
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$DEVELOPMENT_SERVER_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh $DEVELOPMENT_SERVER_USERNAME@$DEVELOPMENT_SERVER_IP docker-compose -f /home/excel/Excel-Events-Service/staging.docker-compose.yml pull
    - ssh $DEVELOPMENT_SERVER_USERNAME@$DEVELOPMENT_SERVER_IP docker-compose -f /home/excel/Excel-Events-Service/staging.docker-compose.yml restart
  only:
    - master@excel-mec/excel-events/excel-events-service
